all:
	g++ editor.cpp -o editor
	g++ n1.cpp -o n1
	g++ n2.cpp -o n2
	g++ reporter.cpp -o reporter
	g++ screen.cpp -o screen
	g++ livetele.cpp -o livetele
	g++ docwriter.cpp -o docwriter
	
	gnome-terminal -e "./editor" --working-directory=/home/mohit/Desktop/CNAssignments/NITWNews
	gnome-terminal -e "./n1" --working-directory=/home/mohit/Desktop/CNAssignments/NITWNews
	gnome-terminal -e "./n2" --working-directory=/home/mohit/Desktop/CNAssignments/NITWNews
	gnome-terminal -e "./screen" --working-directory=/home/mohit/Desktop/CNAssignments/NITWNews
